version: 2

sphinx:
  configuration: doc/conf.py

conda:
  environment: environment.yml

build:
  os: ubuntu-22.04
  tools:
    python: "3.7"
  apt_packages:
    - gcc
    - libgmp3-dev

python:
  install:
    - requirements: doc/requirements.txt
    - requirements: requirements.txt
    - method: pip
      path: .
