version: 2

sphinx:
  configuration: doc/conf.py

conda:
  environment: environment.yml

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"
  apt_packages:
    - gcc
    - libgmp3-dev

python:
  install:
    - method: pip
      path: .
