# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
          persist-credentials: false
          fetch-depth: 0
    
    - uses: conda-incubator/setup-miniconda@v2
      with:
          activate-environment: MPO
          python-version: 3.7

    - name: Install dependencies
      shell: bash -l {0}
      run:  pip install --upgrade pip
      
    - name: Install Settry
      shell: bash -l {0}
      run: pip install -e git+https://github.com/mmihaltz/pysettrie.git#egg=pysettrie
      
      
    - name: Install dependencies 2
      shell: bash -l {0}
      run:  pip install flake8 pytest pathos plotly
            
    - name: Install other dependences 3
      shell: bash -l {0}
      run:  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Install other dependences 4
      shell: bash -l {0}
      run:  conda install -c conda-forge quadprog
      
    - name: Add Paths
      shell: bash -l {0}
      run: conda config --add channels http://conda.anaconda.org/gurobi
    
      
    - name: Install conda packages
      shell: bash -l {0}
      run: conda install numpy gurobi scipy matplotlib numba
    
    - name: pip packages
      shell: bash -l {0}
      run: pip install pypoman
      
    - name: gurobypi package
      shell: bash -l {0}
      run: pip install -i https://pypi.gurobi.com gurobipy
    
    - name: list packages
      shell: bash -l {0}
      run: conda list
    
    - name: Test with pytest
      shell: bash -l {0}
      run: pytest 
        
